language: node_js
node_js:
- '10'
install: npm install
script: npm test
deploy:
  provider: heroku
  api_key:
    secure: rQfy6Gfa8sJkYS/NW757jwZMrG0wOcuqeJZVDSsg6kTmEPsWHSdiM+L4Dmj3eOM0rcsvtzZNQHDu3SAPkxcBQW38WRY9hsr3tpQ4R3jAMFTmlNBEqAld+VBr4ZvVINScrW/L2tjd/7OE3+wnyQYyvUYZJfJVkLnMOLvRf8hzEzNWKbCrWEn6a/O35AXJltt3V0isXWqcycl4eJJpEzA2XODnHb1S+beHXMHwF06RYtZ6RmjMh3sQCXU3U0xPjJneFVtxnKWc5ttcWKV38lR0eR0RYyRXOVkwn4BPK/h/IbZYVSW4ItnGNqlM+MkiY6Ymu0s6py8KvDZO1ajxmJAlg5I5BmifiT0a/EkEUdBJmYUZyuv7ZJfVHACPRF73k8hvBM3UnCeqmb8AzArnTJQ4q9KtJpvR6KC8e99gb4fsXcUgq710NJNicVKSTH/fEwVOAwlU/anKKWtLr9+vB4PEVUFDtTRSbji3rVlVvok9gqydAxZDuqq1hIy5Okp5UFxNWvQ2hUGtEZsgKkTi7OhWxSxRjtti6h1iCaPRqOu4o/Vzo/ZK0UhTVwEndUE8zKNqalcUMfYGJXDlKAVbApdQ1wdHptsajROmeXXjrAozhH2BFTSqM9H1dRGtAtxEhOAwfTuAdE28DavTLVlDow0WQcQ3xBkKooxP8H0AX5Bryv4=
  app: api-megaburguer
