language: node_js
node_js:
- '10'
install: npm install
script: npm test
deploy:
  provider: heroku
  api_key:
    secure: a8cF/D0yq2/+oqS/Uig3HMqsxjHqclaYBG2oBuY0ZBhIFbSUIxSABHKV6RlWnFj60gOl/y9yH6hP+zNxaOI/+L3XX1OYPDvG4lObdUCb0L80uatfEt2o9J6wIO8ihYoLLZmhbB1gJj+mNBH1NUtbfOYjsBJigMeDsbCElV04Af004skTde2CyAtGszUaO/ImODbIz5dunPA5NABl41nUFQof/vdHe2LvNZHZ46qoQsJEIa0pyOlQ0ll60R1mUbgbqGgCO6teS8Qdo9Y0jfjHmTZXZUA2d4ZobWmaQ/V6qEX4sNvExvgpL9pp0OBD0SHpUK34zWIICe1qEOggbGiuP3QG2WfvLQ9ymxhDFuF1CRr2cQNElHBxe8RHfS/t9JLevwpKY1BYhdFdHv2Pr4Kl3mQhT3iboqb3MY3aw/kzouYg7Yr7zGKUKVW70kRJhTJ3CD8yNuQUBdBqvEvrJbQgkzgCUVg9gh6XcYfUpuLMYWEqW1dYlgXGDIUN8yMxw+HolsunCdEXUg5FuW8JUPkPu1NTg/m8PGXFxS4GADZpu1y9n1KFWRbRTds9MRj57OOsOxrJydzmhNW8gV6hrAqa2mbfVzANfPCVSn6pDCD+2IBwh6vlb+2n+1MBw2E4dKCGukMLZocOwljZMGbNbkzpR9sy6Biy5aZM2vldmJI5anA=
  app: api-megaburguer
