language: node_js
node_js:
- '10'
install: npm install
script: npm test
deploy:
  provider: heroku
  api_key:
    secure: sRmvc39sOiU8kDEsgm8U9D5REKwh0mYmlDAq2jRPwDiG3PFTNohiEUhL5S/pj3we1iy3nqSwcWDn7SDkJYEpFjIMHsJMjZ8RuLbqXUY0xfcDH1kIxnVw8HrcanSDufTQEYEU7SW6+IDSSMIiZFruiScxTeaYP2GEIuXMuD6KWNMoJihSVpAkBTisVbfOvepQgt7AfAU+5MgwIvRfLHljEZvP1qul4EF/u3XVbwp46TE0LIoHd+I48W4zyoIuPMvB3wGganSrelgxt5d1zrq0Z2tj8kHMSnx/N220aai7BAMFiNqkN8s5rBaIBPRDvXchzdE3pHtg12MtTeF2MSGsaSlCrkz2x0rv8/3Qyp1s6NAS21HU2QkoDIEB6IC0VnrY0qgaW4JDZDQtqZ/1PL3XTEIfsoaOKpiTpoYpztvIzF+zOYobxFAd4nmn5SP/YGnCC1bSzoeUIDy875Ow+BumLNK2ZYxL0kPOtYrWmA8evwvQIVnqwbsOKR2HXfJ6Np+aWa+G21PKpg4A+A/g/BpdaHAWfUDGUub+OOMIksa3AghBoawGjHhIWaQOnnSwV4K6ZbRLYGu2N5PfAu+vXdSfDAolYSmY2LYFvIJTCslfIWxTy5ry4A1WJj54p6SJdeIUvxlJ/VNmIJT0hO7UcTfZ5Q7tQc/epIP3PWg+vHuH0kI=
  app: api-megaburguer
