language: node_js
node_js:
- '10'
install: npm install
script: npm test
deploy:
  provider: heroku
  api_key:
    secure: UQEGoHqpXEbGInbBK5nBJfz0CQXmh5ev4JRjBb0/5rFUPNacmg7MVhvZsVHSvE84veYmSakTo9v5RNkqbiiX6TteZT3WQTb1RdAarIF7wp6q0ZwBShsGbx/nDY3Il/xDLEM411JT9pZG5QFMo2L6QlcmhD8dNB2sF37iaO+hfMDmVVxFz2oEcdkoAYkscKmcPafCcDccpzK2NYgS+31o78IPQliq+0LFNiQjLKujijOjtBTMiXPCyf217XPpRzNZJAH519EzsDuZUhL9Fc3sOIGYGuRB7DpIoQ1e16DMqjY/afk15lgE/jqNJlfaP8LJ6FVwT2n4wiS/VOPEGcZ/xvymFXccCZZrdiFnCF6r/WMC9DeGhesMIufZ6eG9/DtgnYTzUXSnPNOZn4wE8MHk3hYwQjDZnUd/oEcSdl3uLIEEul8o4g46Gf4a8khCPqk+sqG2kGs4W56ypQB3TrhQ+G0LenPFRf1B6ei7HvUGF1hzHbPAwPuaLY+AjLCzH+bbraX/5oYxPGAxi9sLsKk5jEX860XrqxqH8zQnTIwmtYJM7kMKcxwbZEJHgu76dU84d/yg4p/FJY4M2N1poTujWeorTj1PVoA4pB9JPLIneS2OJ04adP86RPwmNKni7hMhHsggtJ8OLheBXps5ldBd7Q4urG78I5U4VD5aWkOoeIw=
  app: api-megaburguer
